import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/header";
// import Price from "../components/price";

const inter = Inter({ subsets: ["latin"] });

export default function Pricing() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {/* <Price /> */}
      </main>
    </>
  );
}
